stages:
  - build
  - deploy

build_backend:
  stage: build
  script:
    - mvn clean package -DskipTests
    - cp ./target/ssbd02*.jar /ssbd/api/target/ssbd02.jar
  tags:
    - backend-shell
  only:
    - main

deploy_backend:
  stage: deploy
  script:
    - cd /ssbd/docker
    - docker compose build backend
    - docker compose up -d --no-deps --force-recreate backend
    # - mvn liquibase:update
  tags:
    - backend-shell
  only:
    - main