CREATE USER mok WITH ENCRYPTED PASSWORD 'P@ssw0rd';
GRANT CONNECT ON DATABASE ssbd TO mok;
GRANT USAGE ON SCHEMA public TO mok;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO mok;

CREATE USER mod WITH ENCRYPTED PASSWORD 'P@ssw0rd';
GRANT CONNECT ON DATABASE ssbd TO mod;
GRANT USAGE ON SCHEMA public TO mod;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public to mod;